site_name: emailage
site_description: Emailage API client written in Python
site_author: Emailage Dev Team
repo_url: https://github.com/emailage/Emailage_Python
# google_analytics: ['XX-XXXXXXXX-XX', 'auto']

theme: mkdocs

nav:
- Home: html/index.md

- About:
  - 'Release Notes': html/about/changes.html
  - Contributing: html/about/contributing.html
  - License: html/about/license.html
